config/routes.rb
Rails.application.routes.draw do
  resources :questions
  root "questions#index"

  # get "/questions" => "questions#index"
  # get "/questions/new" => "questions#new"
  # get "/questions/:id/edit" => "questions#edit"
  # get "/questions/:id" => "questions#show"
  # post "/questions" => "questions#create"
  # put "/questions/:id" => "questions#update"
  # patch "/questions/:id" => "questions#update"
  # delete "/questions/:id" => "questions#destroy"
  delete "/questions" => "questions#destroy_all"
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :text, presence: true
  validates :option_1, presence: true
  validates :option_2, presence: true
  validates :option_3, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions

  def index
    if params[:order] == "desc"
      @order = "asc"
    else
      @order = "desc"
    end
    @questions = Question.all.order("text " + params[:order])
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      render :show, status: :ok, location: @question
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  # DESTROY_ALL /questions
  def destroy_all
    Question.destroy_all
    redirect_to questions_url, notice: 'Questions were successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text, :option_1, :option_2, :option_3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kuora</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :option_1 %><br>
    <%= f.text_field :option_1 %>
  </div>
  <div class="field">
    <%= f.label :option_2 %><br>
    <%= f.text_field :option_2 %>
  </div>
  <div class="field">
    <%= f.label :option_3 %><br>
    <%= f.text_field :option_3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing <%= pluralize(Question.count, "question") %></h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Option 1</th>
      <th>Option 2</th>
      <th>Option 3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.text %></td>
        <td><%= question.option_1 %></td>
        <td><%= question.option_2 %></td>
        <td><%= question.option_3 %></td>
        <td><%= link_to 'Show', question_path(question) %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Order', questions_path(order: @order) %>
<%= link_to 'New Question', new_question_path %>
<%= link_to 'Destroy_all', questions_path, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<p>
  <strong>Option 1:</strong>
  <%= @question.option_1 %>
</p>

<p>
  <strong>Option 2:</strong>
  <%= @question.option_2 %>
</p>

<p>
  <strong>Option 3:</strong>
  <%= @question.option_3 %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>